### ISSUE TITLE
Viewing Perks and Rewards

### ISSUE THREAD

**Issue by abdulmjunaid** [WSU-4110/finance-buddy#6]
|FR6.  Viewing Perks and Rewards|
|---|
|**Goal**: This use case describes how users will be able to view their perks and rewards based on spending habits.  
**Stakeholders:** Customers|
| **Description:** Once the user has successfully had two bank statements, they will have access to the perks and rewards module in the main dashboard. Under this dashboard their progress on unlocking various perks and rewards will be shown. This progress will be shown as a bar, and when the user reaches the perk or reward a small animation will be played congratulating the user. If the user does not have two bank statements the perks and rewards module will be inaccessible. If the user tries to click on the module they will be informed that they do not have enough bank statements.   |
| **Origin:** Project proposal|
| **Version:** 1.0  |
|**Date:** 09/27/2022
|  **Priority:** 1 |

**Comment by bigdog765** [comment]
Not completed
